Misc fixes
ProteinsWebTeam/interpro7-client pull request #338
Opened 2021-04-26 12:43 UTC by matthiasblum

A few fixes/improvements for minor issues.

2021-05-20 13:54 UTC, CodeGit requested changes
When viewing the URL: http://localhost:8000/interpro/protein/reviewed/A0A023GS28/similar_proteins/#table

I saw the following error:
```
react_devtools_backend.js:2557 Warning: Cannot update a component (`DynamicTooltip`) while rendering a different component (`_DataProvider`). To locate the bad setState() call inside `_DataProvider`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at _DataProvider (http://localhost:8000/interpro/js/domain-architecture-subpage~ida-results~similar-proteins-subpage.module.domain-architecture-subpage~ida-results~similar-proteins-subpage.3f9.js:992:5)
    at UnconnectedErrorBoundary (http://localhost:8000/interpro/js/main.module.main.320.js:137427:5)
    at DataWrapper (http://localhost:8000/interpro/js/about-page~download-form~download-summary~entry-page~help-page~home-page~ida-results~ipscan-search~i~f90ffb1d.module.about-page~download-form~download-summary~entry-page~help-page~home-page~ida-results~ipscan-search~i~f90ffb1d.d98.js:416:9)
```

The text Reviewed button in the button could do with a bit of space added between the text and the square switch.

![Screenshot 2021-05-20 at 14 51 04](https://user-images.githubusercontent.com/892047/118991015-484c2d80-b97b-11eb-90bc-5ee86105b7c3.png)

2021-05-20 15:43 UTC, Swaathik commented
The console error seems to be from here - https://github.com/ProteinsWebTeam/interpro7-client/blob/master/src/components/SimpleCommonComponents/DynamicTooltip/index.js#L118. SetState of dynamic-tooltip is triggered from DataProvider while the former is already rendering. May be we could create a separate issue for the refactoring.

2021-05-21 09:35 UTC, CodeGit approved these changes

2021-05-21 09:39 UTC, CodeGit approved these changes

2021-05-21 10:05 UTC, merged