Adding split screen functionality to the alphafold viewer
ProteinsWebTeam/interpro7-client pull request #448
Opened 2023-01-06 16:18 UTC by gustavo-salazar

FIX #444 
It is useful to see the structure viewer side by side with the protein feature viewer. One way to do it is to fullscreen them and split the screen 50/50. This functionality was already available when displaying PDB structures, but it was missing for AlphaFold models, hence this PR.

2023-01-11 16:50 UTC, matthiasblum requested changes
Looks nice, thanks.

In full screen mode, the control buttons (PDB/mmCIF download buttons, reset image button, etc.) are hidden. However, in split full screen mode that are displayed... including the "view the structure in full screen mode", although we are already technically in a full screen mode. And clicking this button just hide the protein viewer.

I think it'd be better if the two screen modes had the same behavior with respect to the control buttons.

2023-01-11 16:50 UTC, matthiasblum commented on src/components/AlphaFold/Model/index.js
>        </h3>
Maybe hide this in slit-screen mode?

2023-01-13 11:45 UTC, gustavo-salazar commented
OK, changes done, please check again.

2023-01-16 16:49 UTC, matthiasblum commented
Thank you. Looks good. :+1:

2023-01-16 16:50 UTC, matthiasblum approved these changes
Looks good. Thank you.

2023-01-16 16:50 UTC, merged