Contact us page
ProteinsWebTeam/interpro7-client pull request #558
Opened 2024-01-05 14:14 UTC by gustavo-salazar

A page with all the contact details.

FIX #531

2024-01-05 15:41 UTC, typhainepl requested changes
A page that was definitely missing!
I added a few comments, notably Twitter is now called "X" and I believe we should change the logo.

2024-01-05 15:41 UTC, typhainepl commented on src/pages/Contact/index.tsx
> +          <Link href="mailto: interhelp@ebi.ac.uk">
I wouldn't add the helpdesk email address, as this is likely to lead to receive more spams from robots

2024-01-05 15:41 UTC, typhainepl commented on src/pages/Contact/index.tsx
> +          <Link href="mailto: pfam-help@ebi.ac.uk">
see previous comment

2024-01-05 15:41 UTC, typhainepl commented on src/pages/Contact/index.tsx
> +          <Twitter />
Twitter is now called X and the term "tweet" as been changed to "post"

2024-01-05 15:41 UTC, typhainepl commented on src/pages/Contact/index.tsx
> +          <Twitter handler="PfamDB" />
Twitter is now called X and the term "tweet" as been changed to "post"

2024-01-05 15:41 UTC, typhainepl commented on src/components/Twitter/index.tsx
> +        Tweets by @{handler}
Change to "Posts by"

2024-01-05 15:41 UTC, typhainepl commented on src/components/Twitter/__snapshots__/test.js.snap
> +    Tweets by @
Change to "Posts by"

2024-01-05 22:37 UTC, matthiasblum commented
Is an extra item in the menu and an extra page _really_ what we need?

We already have the _Help_ and _About_ buttons, each with their own submenu. That's twelve pages. Some contain links to ReadTheDocs. Some actually _import_ their content from ReadTheDocs.

We have a link to the support & feedback form:

* in the [FAQ](https://www.ebi.ac.uk/interpro/help/faqs/) (imported from ReadTheDocs)
* on the [Training page](https://www.ebi.ac.uk/interpro/help/training/) (imported from ReadTheDocs)
* on the [Documentation page](https://www.ebi.ac.uk/interpro/help/documentation/)
* and now on the new Contact Us page

Also, the Help/About section are kind of overlapping/interconnecting (the content between `Help >FAQ` and `About > InterPro` is quite redundant).

Maybe we could simplify this part of the website, e.g. one "Help center" page, that contains:

- links to training material (tutorial, webinars, links to future courses)
- links to various documentations (InterPro, Pfam, InterProScan)
- links to InterPro/Pfam support & feedback forms, and social medias

2024-01-10 15:57 UTC, gustavo-salazar commented
I was thinking about @matthiasblum comment, and given that we forgot to talk about it in standup I'll write it here.

I think that a bit of redundancy on training and help materials is not a bad thing, as long as the users manage to find the info they need. But also think that restructuring into a `Help Centre` or something like it is not a bad idea as it might again help user to find the help they need.

The suggested page is a quick solution to the fact that the contact information is quite hidden, even if is replicated in multiple places.

So, I suggest going ahead with the content of this PR, and implementing @typhainepl suggestions. But also create a story to plan restructuring that area, maybe following @matthiasblum suggestion in this PR, but also giving a bit more thought to it and see if that suffices the needs of help & documentation.

What do you think?

2024-01-10 22:46 UTC, matthiasblum commented
> 
> So, I suggest going ahead with the content of this PR, and implementing @typhainepl suggestions. But also create a story to plan restructuring that area, maybe following @matthiasblum suggestion in this PR, but also giving a bit more thought to it and see if that suffices the needs of help & documentation.
> 
> What do you think?

Yep, sounds good. :+1:

2024-01-11 16:19 UTC, typhainepl commented
It looks good to me.
I guess we could remove the `Contact us` link from the `Documentation` and `FAQ` pages.

2024-01-12 10:46 UTC, gustavo-salazar commented
> It looks good to me. I guess we could remove the `Contact us` link from the `Documentation` and `FAQ` pages.

I'm going to leave them there. I still think redundancy is a good thing in this case. But definitely something to consider while planning for the "Help center" idea.

BTW, I have opened issue #563 for the Help center idea.

2024-01-12 10:46 UTC, merged