Ts migrations for Menu
ProteinsWebTeam/interpro7-client pull request #562
Opened 2024-01-10 15:42 UTC by gustavo-salazar

Migrating to TS and vs framework the components related to the menus:
* `src/components/Menu/DynamicMenu`
* `src/components/Menu/EBIMenu`
* `src/components/Menu/EntitiesMenu`
* `src/components/Menu/InterProMenu`
* `src/components/Menu/MenuItem`
* `src/components/Menu/SideMenu`
* `src/components/Menu/SideMenu/ServerStatus`
* `src/menuConfig`

Deleted because it wasn't in use anymore:
* `src/components/Menu/SingleEntityMenu`

Other fixes:
* The hamburger menu button now toggles the menu on and off
* `main` is not mandatory in `InterProPartialDescription` type. As some of the updated links here showed.

2024-01-11 11:18 UTC, matthiasblum approved these changes
LGTM. 

> The hamburger menu button now toggles the menu on and off

You mean this one?

![image](https://github.com/ProteinsWebTeam/interpro7-client/assets/2097501/d3252441-a9d8-4df5-9a65-1ac8b680013c)

![image](https://github.com/ProteinsWebTeam/interpro7-client/assets/2097501/9675c762-fd8b-4aa6-91a1-5cd1f254cc44)

It wasn't already toggling the side menu on and off? :raised_eyebrow:

2024-01-11 11:18 UTC, matthiasblum commented on src/components/Menu/SideMenu/index.tsx
>                title="💡 What is the status of external dependencies?"
```suggestion
              title="💡 What is the status of external services?"
```

2024-01-11 11:18 UTC, matthiasblum commented on src/components/Menu/SideMenu/index.tsx
> +              body="The green signal is displayed when an external dependency is available whist a red signal indicates that InterPro cannot connect to the resource."
```suggestion
              body="A green signal indicates that the external service is online and available. A red signal indicates that InterPro is unable to connect to the external resource."
```

2024-01-11 11:23 UTC, gustavo-salazar commented
> It wasn't already toggling the side menu on and off? 🤨

Nope, somehow was only opening it, even if the animation made it an X the action was still to open 🤷🏽

2024-01-11 11:28 UTC, matthiasblum commented
> > It wasn't already toggling the side menu on and off? 🤨
> 
> Nope, somehow was only opening it, even if the animation made it an X the action was still to open 🤷🏽

I'll take you word for it, clicking the cross button closes the menu on my Firefox and Chromium :man_shrugging:.

2024-01-11 16:55 UTC, typhainepl requested changes
For some reason the `Function` right column isn't aligned anymore in the Protein page. Looking deeper in the HTML content, it looks like a div with the class `content Description_style__content___b2` has been added. Example: http://localhost:8080/interpro/protein/reviewed/O00167/

Everything else looks alright to me.

2024-01-11 17:01 UTC, typhainepl commented
The cross wasn't closing the menu when the header was collapsed on my browser, but it was working fine in the expanded view. It's working fine now.

2024-01-12 09:46 UTC, typhainepl commented
Not directly related to the menu TS migration, but to the use of the Visual Framework. On the Alignment subpage of Pfam pages, the `Legends` button has been changed, but not the `Downloads`. Also, the `conservation` checkbox is working fine locally, but it is disabled in the future branch. Example: http://wp-np3-bd/future/entry/pfam/PF00002/entry_alignments/?type=seed

2024-01-12 10:53 UTC, gustavo-salazar commented
> For some reason the `Function` right column isn't aligned anymore in the Protein page. Looking deeper in the HTML content, it looks like a div with the class `content Description_style__content___b2` has been added. Example: http://localhost:8080/interpro/protein/reviewed/O00167/

Good point, that is more to do with the design changes for the `AI generated` descriptions, because we use the same component here. I will make sure to correct it.

2024-01-12 11:31 UTC, gustavo-salazar commented
> Not directly related to the menu TS migration, but to the use of the Visual Framework. On the Alignment subpage of Pfam pages, the `Legends` button has been changed, but not the `Downloads`. 

@typhainepl  I haven't migrated the alignment page yet, however, I migrated the dropdown buttons causing the clear mismatch. I just styled that button to fix it. But unfortunately, I think we are going to see more of these cases while in the migration period. Please report them as usual, so I can correct them.

>Also, the `conservation` checkbox is working fine locally, but it is disabled in the future branch. Example: http://wp-np3-bd/future/entry/pfam/PF00002/entry_alignments/?type=seed

Damn, I thought we had fixed that one already. It is related to the way the conservation gets calculated in the background using a web worker, and how is not been deployed properly for production. I'll open an issue for it to work on it separately.

2024-01-12 11:53 UTC, typhainepl approved these changes
Looking good to me.

2024-01-12 12:06 UTC, merged