New export button
ProteinsWebTeam/interpro7-client pull request #662
Opened 2024-09-05 14:56 UTC by apolignano

Updated export buttons following [IBU-11326](https://www.ebi.ac.uk/panda/jira/browse/IBU-11326)

2024-09-09 12:32 UTC, apolignano commented
As previously discussed, I updated the download menu to show only one script generation button (with JSON default), instead of having it for each data format.

We now basically have two types of buttons: 

- download buttons (FASTA, TSV, JSON);
- external link buttons (web APIs and script generator).

To have the second type of buttons I modified the APIViewButton. I renamed it and refactored it so that it can also accommodate for the script generation case. 

The reason why you see many file changed is because of all the imports and snapshots that needed to be updated, the addition of the script generation button to every "browsing page" and some minor changes to address warnings along the way.

![image](https://github.com/user-attachments/assets/80cbc5e2-406d-4531-b3df-3afb4b5ed6e7)

Not sure about the the "API" and "CODE" names though. Waiting for feedback on that.

2024-09-16 17:54 UTC, matthiasblum requested changes
Looks nice. There are few things that need to be changed, see comments/suggestions.

Also, add the `width` and `white-space` rules to `src/components/SimpleCommonComponents/DropDownButton/style.css`:

```css
  & .dropdown-pane {
    z-index: var(--z-index-over-plus); /* so sticky header stay on top*/
    border: 2px solid var(--colors-submain);
    width: auto;
    white-space: nowrap;
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Entry/DomainArchitectures/Options/index.tsx
>              <label htmlFor="json">JSON</label>
```suggestion
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Entry/DomainArchitectures/Options/index.tsx
> +            <label htmlFor="json">JSON</label>
```suggestion
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Entry/DomainArchitectures/Options/index.tsx
>              <label htmlFor="api">API</label>
```suggestion
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Entry/DomainArchitectures/Options/index.tsx
> +                url={getAPIURL(api, entryLocation, search)}
Make sure that `getAPIURL` returns the URL of the public API, not the one used by the website (`wwwapi`):

```ts
const getAPIURL = (
  { protocol, hostname, port, root }: ParsedURLServer,
  entryLocation?: EndpointLocation,
  search?: InterProLocationSearch,
) => {
  const description: InterProPartialDescription = {
    main: { key: 'entry' },
    entry: {
      ...(entryLocation || {}),
      detail: undefined,
    },
  };
  return toPublicAPI(
    format({
      protocol,
      hostname,
      port,
      pathname: root + descriptionToPath(description),
      query: entryLocation?.accession ? { ida: '' } : search,
    })
  );
};
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Matches/index.tsx
The `<label>` elements above each `<FileExporter>` need to be removed otherwise the label is displayed twice, e.g. http://localhost:8080/interpro/set/pfam/CL0001/entry/pfam/#table

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Taxonomy/List/index.tsx
> +              <ExternalExportButton type={'api'} url={urlToExport} />
Need to "sanitize" the URL with `toPublicAPI()`.

2024-09-16 17:54 UTC, matthiasblum commented on src/subPages/SimilarProteins/Table/index.tsx
>          </Exporter>
```suggestion
            <ExternalExportButton
              type={'api'}
              url={getAPIURLForSimilarProteins(api, ida, db)}
            />
            <ExternalExportButton
              search={search}
              type={'scriptgen'}
              subpath={descriptionToPath(description)}
            />
          </div>
        </Exporter>
```

Move second `ExternalExportButton` within the same group.

2024-09-16 17:54 UTC, matthiasblum commented on src/pages/Structure/index.tsx
> +              <ExternalExportButton type={'api'} url={url} />
Need to sanitize the URL with `toPublicAPI()`.

2024-09-16 17:54 UTC, matthiasblum commented on src/pages/Proteome/index.tsx
> +              <ExternalExportButton type={'api'} url={url} />
Need to sanitize URL with `toPublicAPI()`.

2024-09-16 17:54 UTC, matthiasblum commented on src/pages/Protein/index.tsx
> +              <ExternalExportButton type={'api'} url={url} />
Need to sanitize URL with `toPublicAPI()`.

2024-09-16 17:54 UTC, matthiasblum commented on src/pages/Entry/index.tsx
> +              <ExternalExportButton type={'api'} url={data.url} />
Need to sanitize URL with `toPublicAPI()`.

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Table/Exporter/ExternalExportButton/index.tsx
> +          : 'Generate script to get JSON data'
```suggestion
          ? 'Open results in the browsable API'
          : 'Generate a script to download results on the command line'
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Table/Exporter/ExternalExportButton/index.tsx
> +            <div> {type == 'api' ? 'API' : 'CODE'} </div>
```suggestion
            <div> {type === 'api' ? 'Browsable API' : 'Script generator'} </div>
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Table/Exporter/ExternalExportButton/index.tsx
> +        type == 'api'
```suggestion
        type === 'api'
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Table/Exporter/ExternalExportButton/index.tsx
> +          type == 'scriptgen' && search !== undefined
```suggestion
        href={type === 'api' ? url : ''}
        to={
          type === 'scriptgen' && search !== undefined
```

2024-09-16 17:54 UTC, matthiasblum commented on src/components/Table/Exporter/ExternalExportButton/index.tsx
> +                  `icon-${type == 'api' ? 'globe' : 'code'}`,
```suggestion
                  `icon-${type === 'api' ? 'globe' : 'code'}`,
```

2024-09-20 11:47 UTC, matthiasblum approved these changes
LGTM.

Minor comments/suggestions, but nothing big.

2024-09-20 11:47 UTC, matthiasblum commented on src/components/File/FileButton/index.tsx
> +
```suggestion

  if (downloading)
    label = 'Generating ';
  else if (!!successful)
    label = 'Save '
  else
    label = 'Generate ';
    
```

2024-09-20 11:47 UTC, matthiasblum commented on src/components/File/FileButton/index.tsx
> +          <div>{fileType.replace('accession', 'TSV').toUpperCase()}</div>
```suggestion
          <div>{label}{fileType.replace('accession', 'TSV').toUpperCase()}</div>
```

2024-09-20 15:03 UTC, merged