Reorganization of tracks v2
ProteinsWebTeam/interpro7-client pull request #667
Opened 2024-10-08 15:15 UTC by apolignano

This PR addresses the changes requested on the reorganization of tracks v1.0:

- Domains and families have been merged with their respective representative ones. The representative are shown by default. The others are shown as a dropdown;
- Homologous superfamilies have been integrated into the domains section;
- Labels for unintegrated entries have been added to improve how groups are spaced and visualized;
- Default order for the main section is now: [AlphaFold confidence, Families, Domains, IDR, Conserved Residues]
- MobiDB-lite parent track is now visible again;
- PIRSR residues are now grouped by description, start and end position to avoid duplicates. A "grouping label" has been added to separate them from those coming from CDD.

![image](https://github.com/user-attachments/assets/072b0e4f-4d4e-4690-9e08-4b76288dad17)
![image](https://github.com/user-attachments/assets/870dca1d-c22b-48af-9508-f1ee8b49e143)

2024-10-15 13:51 UTC, matthiasblum requested changes
Looks good overall. A few minor comments/questions to address/answer.

2024-10-15 13:51 UTC, matthiasblum commented on src/components/Nightingale/InterProTrack/index.tsx
> +export default NightingaleInterproTrack;
Is it because of the patch that we can no longer use a `Memo`?

2024-10-15 13:51 UTC, matthiasblum commented on src/components/ProteinViewer/LabelsInTrack/ResidueLabel/index.tsx
> +                : r.accession + 'test'}
Besides the `test` incorrectly added after the accession, I don't think it's a problem to have long descriptions.

```suggestion
                  ? r.description.charAt(0).toUpperCase() + r.description.slice(1)
                  : r.accession}
```

2024-10-15 13:51 UTC, matthiasblum commented on src/components/ProteinViewer/RepresentativeDomainsTrack/index.tsx
> +        <b>Representative</b>
Ideally, we could pass the label as a props of `RepresentativeDomainsTrack` so the representative domains track is labelled "Representative domains", and similarly for representative families.

2024-10-15 13:51 UTC, matthiasblum commented on src/components/ProteinViewer/index.tsx
>      'homologous superfamily': false,
Can be removed as all regions under `homologous superfamily` are now displayed under `domains`.

2024-10-15 13:51 UTC, matthiasblum commented on src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx
>    'homologous_superfamily',
```suggestion
```

2024-10-15 13:51 UTC, matthiasblum commented on src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx
> +    if (currentResidue.source_database == 'pirsr') {
```suggestion
    if (currentResidue.source_database === 'pirsr') {
```

2024-10-15 13:51 UTC, matthiasblum commented on src/components/ProteinViewer/LabelsInTrack/ExceptionalLabels/index.tsx
> +            processedAccession == 'PIRSR_GROUP' ? 'pirsr-label' : '',
```suggestion
            processedAccession === 'PIRSR_GROUP' ? 'pirsr-label' : '',
```

2024-10-15 13:51 UTC, matthiasblum commented on src/components/ProteinViewer/TracksInCategory/index.tsx
> +                        }
```suggestion
                        samesize={entry.source_database !== 'mobidblt'}
```

2024-10-15 13:51 UTC, matthiasblum commented on src/utils/text/index.js
> +  else if (entry.accession) text += entry.accession;
This makes the "label by" selection under "options" useless.

I think we should avoid showing the accession indeed, but this requires to remove it from the "Label By" options list.

2024-10-15 13:51 UTC, matthiasblum commented on src/utils/text/index.js
> +  }
Instead of truncating the text, add the accession if both the short name and long name aren't available.

2024-10-15 13:51 UTC, matthiasblum commented on src/components/Related/DomainsOnProtein/mergeResidues.ts
> +        residueEntry.accession = `${location.accession || residue.accession}`;
The `.${i}` is no longer necessary?

2024-10-15 13:51 UTC, matthiasblum commented on src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx
Two `==` to replace by `===` in the `sortTracks()` function.

https://github.com/ProteinsWebTeam/interpro7-client/blob/dae15cc4e11f2a08440d68856f65498a3cd76cfe/src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx#L88-L106

2024-10-18 09:47 UTC, matthiasblum commented on src/components/Nightingale/InterProTrack/index.tsx
> +export default NightingaleInterproTrack;
@apolignano ?

2024-10-21 10:04 UTC, matthiasblum requested changes
Matches of type _repeat_ can be selected as representative domains. For instance, in the case of A0A010RW41, the [live website](https://www.ebi.ac.uk/interpro/protein/UniProt/A0A010RW41/) shows all representative domains, including the Pfam ANAPC8 repeat:

![image](https://github.com/user-attachments/assets/c4535469-2a4c-4ffb-9206-498bac8b7525)

However, this PR only considers matches of type _domain_ leading to an incomplete representative domain track:

![image](https://github.com/user-attachments/assets/84548c0b-4c13-483d-80fd-9eb205bccdc0)

---

Another bug is that annotations from ELM are displayed twice: once under "Short Linear Motifs" (as expected), and once under "Other Features". Example: `P00549`.

2024-10-23 09:26 UTC, matthiasblum approved these changes
Looks good to me.

Made minor suggestions that should be committed before merging.
Also please, review and merge #669 before merging this PR.

A minor bug that can be addressed before merging is that the MobiDB-lite domains are inconsistently colored when choosing the color by domain relationship. The top track is in grey and the following are in green. Example with `Q15648`:

![image](https://github.com/user-attachments/assets/cd8d6dd0-27bf-4b7a-8a22-c543f0f6edfb)

2024-10-23 11:51 UTC, apolignano commented
Fixed color by domain relationship for the MobiDB-Lite track

2024-10-24 12:53 UTC, matthiasblum approved these changes
Looks good to me. Feel free to merge and deploy on staging/wwwdev. Thanks!

2024-10-25 08:54 UTC, merged