ShowMore in redux state, switch styling
ProteinsWebTeam/interpro7-client pull request #678
Opened 2024-11-12 13:21 UTC by apolignano

2024-11-12 13:27 UTC, apolignano commented
- The ShowMore button state is now saved in the Global Redux State, allowing users to keep the preferred view.
- The styling of the toggle button could be up for discussion to make it as similar as possible to the other VF components.

2024-11-21 17:27 UTC, matthiasblum requested changes
The switch works as intended, but there are a few things that could be improved

1. it looks like you have re-implemented a switch button. Can you use the [`ToggleSwitch`](https://github.com/ProteinsWebTeam/interpro7-client/blob/master/src/components/ToggleSwitch/index.tsx) component instead?
2. The More/Less option isn't so clear. We could add a label _Feature display_ in front of the switch and the options of the switch would be _Overview_ and _Full_.

2024-11-22 14:10 UTC, apolignano commented
Unfortunately, the ToggleSwitch component doesn't look great when positioned there, as it only accepts three sizes and none of them match the Option menu button. I've tried to pass an height prop but you end up having to play around too much with margins, CSS vars, etc.. Tried the label too, and it looks even worse IMO. 

Less and More are renamed to Overview and Full and the color-changing behavior of ToggleSwitch has been implemented.

![Screenshot 2024-11-22 at 12 26 40](https://github.com/user-attachments/assets/428429a0-722d-43e7-b436-d512e5029b18)

![Screenshot 2024-11-22 at 12 28 09](https://github.com/user-attachments/assets/b67a4c7d-b9c9-4417-a152-fee546adb607)

Let me know if it works!

2024-11-25 12:35 UTC, matthiasblum reviewed
Looks better. I suggested a few changes that I think could improve the UI. Please have a look and let me know if you agree with them.

2024-11-25 12:35 UTC, matthiasblum commented on src/components/ProteinViewer/ShowMoreTracks/index.tsx
>    );
Minor style changes, and add a label in front of the switch (not the best UI, but I think we need a label):

```ts
  return (
    <>
      Feature display:
      <div onClick={handleClick}>
        <div
          className={css('showmore-toggle-outer', showMore ? 'full' : 'overview')}
        >
          <div
            className={css('showmore-toggle-inner', showMore ? 'moved' : '')}
          />
          <span style={{ marginLeft: showMore ? '5px' : '33px' }}>
          {showMore ? 'Full' : 'Overview'}
        </span>
        </div>
      </div>
    </>
  );
```

2024-11-25 12:35 UTC, matthiasblum commented on src/components/ProteinViewer/ShowMoreTracks/style.css
> +  width: 105px;
```suggestion
  width: 118px;
```

2024-11-25 12:35 UTC, matthiasblum commented on src/components/ProteinViewer/ShowMoreTracks/style.css
> +  width: 15px;
```suggestion
  width: 28px;
```

2024-11-25 15:05 UTC, merged